build_system = "ninja"
compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_[AC]C.*" = "int"
ABS = "int"
ABS_ALT = "int"
SQ = "int"
ARRAY_COUNT = "int"
ARRAY_COUNTU = "int"
CLAMP = "int"
NULL = "int"
FR_POS_FRUSTRATIO_3 = "int"
FR_NEG_FRUSTRATIO_3 = "int"

[decompme.compilers]
"tools/ido7.1/cc" = "ido7.1"
